name: BayAreaCarGuy
favicon: null
layout_spectrum: 0.99422
typography_spectrum: 0.6281
title: BayAreaCarGuy.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffde7'
    - '#000000'
    - '#75a98b'
    - '#5c493c'
    - '#ed9f6e'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
