name: BayAreaCarGuy
favicon: null
layout_spectrum: 0.99422
typography_spectrum: 0.6281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434955'
    - '#060606'
    - '#343744'
    - '#696e77'
    - '#1d1d1a'
  brandStrength: 0
  lightness: 0.5327914140652865
  saturation: 0.8125
  rhythmicContrast: 0.9599220545496792
purpose: []
