name: BayAreaCarGuy
favicon: null
layout_spectrum: 0.99422
typography_spectrum: 0.3834
title: BayAreaCarGuy.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#022061'
    - '#0c5ab5'
    - '#2dfffe'
    - '#1a9bf3'
    - '#cffefe'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
