name: BayAreaCarGuy
favicon: null
layout_spectrum: 0.75529
typography_spectrum: 0.3834
title: BayAreaCarGuy.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040601'
    - '#5581b2'
    - '#002c9f'
    - '#de906a'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
